use_frameworks!

platform :ios, '8.0'

target 'YRNavigationBarPure_Example' do
  pod 'YRNavigationBarPure', :path => '../'

  target 'YRNavigationBarPure_Tests' do
    inherit! :search_paths

    
  end
end
